# Generated by Django 5.0.6 on 2024-06-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='store',
            field=models.ManyToManyField(to='main_app.store'),
        ),
    ]
